Repository UnifiedCalculation/UniCalc_Frontend, pull requests merged in 2020-05, with the labels that each got.

#49 Article administration
  .gitignore
  .idea/.gitignore
  package-lock.json
  src/backendMock/db.json
  src/backendMock/routes.json
  src/components/connectionHandler/connectionHandler.js
  src/components/layouts/ProductAdministration/ProductOverview.js
  src/components/layouts/ProductAdministration/addNpkProductDialog.js
  src/components/layouts/ProductAdministration/addProductDialog.js
  src/components/layouts/ProductAdministration/productTable.js
  src/components/layouts/header/header.js
  src/components/selectArticleDialog/selectArticleDialog.js
  src/components/singlePage/singlePage.js
Labels: enhancement

#52 User administration
  src/backendMock/db.json
  src/components/connectionHandler/connectionHandler.js
  src/components/dynamicDialog/dynamicDialog.js
  src/components/layouts/adminOptions/adminOptions.js
  src/components/layouts/adminOptions/articleAdministration/ProductOverview.js
  src/components/layouts/adminOptions/articleAdministration/addNpkProductDialog.js
  src/components/layouts/adminOptions/articleAdministration/addProductDialog.js
  src/components/layouts/adminOptions/articleAdministration/productTable.js
  src/components/layouts/adminOptions/userAdministration/employeeDialog.js
  src/components/layouts/adminOptions/userAdministration/userOverview.js
  src/components/layouts/adminOptions/userAdministration/userTable.js
  src/components/layouts/userAdministration/userAdd.js
  src/components/layouts/userAdministration/userEdit.js
  src/components/layouts/userAdministration/userOverview.js
  src/components/layouts/userAdministration/userTable.js
  src/components/singlePage/singlePage.js
Labels: enhancement

#69 New user role payload
  src/backendMock/db.json
  src/components/contractDisplay/contractDisplay.js
  src/components/dynamicEntry/dynamicEntry.js
  src/components/header/header.js
  src/components/invoiceDisplay/invoiceDisplay.js
  src/components/offerCards/offerCards.js
  src/components/offerDisplay/offerDisplay.js
  src/components/singlePage/singlePage.js
Labels: enhancement

#73 Refactors connection handler to match backend verison
  src/components/connectionHandler/connectionHandler.js
Labels: enhancement

#78 Fixes bad path for article update
  src/components/dynamicEntry/dynamicEntry.js
  src/components/invoiceDisplay/invoiceDisplay.js
  src/components/offerDisplay/offerDisplay.js
Labels: bugfix

#79 Fixes path problems, changes icons
  src/components/connectionHandler/connectionHandler.js
  src/components/dynamicEntry/dynamicEntry.js
  src/components/offerCards/offerCards.js
Labels: bugfix, enhancement

#80 Fixes path and payload bug
  src/components/dynamicEntry/dynamicEntry.js
  src/components/newEntrySegmentDialog/newEntrySegmentDialog.js
  src/components/projectDisplay/projectDisplay.js
  src/components/singlePage/singlePage.js
Labels: bugfix

#81 Bugfixes and logging
  src/components/dynamicEntry/dynamicEntry.js
  src/components/invoiceDisplay/invoiceDisplay.js
  src/components/newEntrySegmentDialog/newEntrySegmentDialog.js
  src/components/offerDisplay/offerDisplay.js
  src/components/projectDisplay/projectDisplay.js
  src/components/singlePage/singlePage.js
Labels: bugfix, documentation

#85 Fixes missing parameters
  src/components/comparisonTool/comparisonTool.js
  src/components/contractDisplay/contractDisplay.js
Labels: bugfix

#86 Fixes request being sent to early
  src/components/articleTable/articleTableEntry.js
  src/components/comparisonTool/comparisonTool.js
Labels: bugfix

#87 Removes swipeable views because it doesnt work
  package-lock.json
  package.json
  src/components/comparisonTool/comparisonTool.js
Labels: bugfix

#88 Fixes bug where tabs wouldn't switch
  src/components/comparisonTool/comparisonTool.js
Labels: bugfix

#91 Fixes bug where data was overwritten
  src/components/comparisonTool/comparisonTool.js
  src/components/connectionHandler/connectionHandler.js
  src/components/header/header.js
  src/components/newProjectDialog/newProjectDialog.js
Labels: bugfix

#92 Fixes to logout and entry creation
  src/components/comparisonTool/comparisonTool.js
  src/components/header/header.js
Labels: bugfix

#93 Fixes null check
  src/components/layouts/adminOptions/articleAdministration/productTable.js
Labels: bugfix

#94 Fixes npk submit payload
  src/components/layouts/adminOptions/articleAdministration/addNpkProductDialog.js
  src/components/layouts/adminOptions/articleAdministration/addProductDialog.js
Labels: bugfix

#95 More logging for npk dialog
  src/__tests__/LoginForm.js
  src/__tests__/OfferDisplay.js
  src/__tests__/RegistrationForm.js
  src/__tests__/SelectArticleDialog.js
  src/components/layouts/adminOptions/articleAdministration/addNpkProductDialog.js
Labels: bug

#97 Fixes article creation and display bug
  src/components/layouts/adminOptions/articleAdministration/addNpkProductDialog.js
  src/components/layouts/adminOptions/articleAdministration/productTable.js
Labels: bugfix

#98 Adds back npk id
  src/components/layouts/adminOptions/articleAdministration/addNpkProductDialog.js
Labels: bugfix

#99 Adds new article umber parsing
  src/components/layouts/adminOptions/articleAdministration/productTable.js
Labels: enhancement

#100 Fixes name formatting + wrong payload
  src/components/comparisonTool/comparisonTool.js
  src/components/newProjectDialog/newProjectDialog.js
Labels: bugfix

#101 Adds back in request call
  src/components/comparisonTool/comparisonTool.js
Labels: bugfix

#102 Fixed missing length
  src/components/comparisonTool/comparisonTool.js
Labels: bugfix

#103 Fixes dialog not closing
  src/components/comparisonTool/comparisonTool.js
  src/components/dynamicEntry/dynamicEntry.js
Labels: bugfix
