Repository UnifiedCalculation/UniCalc_Frontend, pull requests merged in 2020-04, with the labels that each got.

#11 Development
  src/App.js
  src/__tests__/LoginForm.js
  src/components/loginForm/loginForm.js
  src/components/singlePage/singlePage.js
Labels: enhancement

#12 Fixed unit tests
  src/App.js
  src/__tests__/LoginForm.js
Labels: bugfix

#15 Create modal component
  .github/workflows/npmTest.yml
  package-lock.json
  package.json
  src/__tests__/Alert.js
  src/components/Alert/alert.css
  src/components/alert/alert.js
  src/components/loginForm/loginForm..js
  src/components/singlePage/singlePage.js
Labels: enhancement

#17 New project dialog
  package-lock.json
  package.json
  src/__tests__/NewProjectDialog.js
  src/components/Alert/alert.css
  src/components/alert/alert.js
  src/components/newProjectDialog/newProjectDialog.js
  src/components/singlePage/singlePage.js
Labels: enhancement

#18 Navigation
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/layouts/dashboard.js
  src/components/layouts/navigation.js
  src/components/singlePage/singlePage.js
  src/index.js
  src/logo.svg
Labels: enhancement

#29 Segment entry dialog
  src/__tests__/NewEntrySegmentDialog.js
  src/components/newEntrySegmentDialog/newEntrySegmentDialog.js
Labels: enhancement

#39 Register user
  src/components/layouts/userAdministration/userAdd.js
  src/components/layouts/userAdministration/userEdit.js
  src/components/layouts/userAdministration/userOverview.js
  src/components/layouts/userAdministration/userTable.js
  src/components/layouts/userOptions/userOptions.js
  src/components/singlePage/singlePage.js
Labels: enhancement

#37 Whole lot of code refactor
  package-lock.json
  package.json
  src/App.js
  src/__tests__/Alert.js
  src/__tests__/DynamicDialog.js
  src/__tests__/NewEntrySegmentDialog.js
  src/__tests__/NewOfferDialog.js
  src/__tests__/NewProjectDialog.js
  src/__tests__/SelectArticleDialog.js
  src/components/alert/alert.js
  src/components/dynamicDialog/dynamicDialog.js
  src/components/loginForm/loginForm.css
  src/components/loginForm/loginForm.js
  src/components/newEntrySegmentDialog/newEntrySegmentDialog.js
  src/components/newOfferDialog/newOfferDialog.js
  src/components/newProjectDialog/newProjectDialog.js
  src/components/selectArticleDialog/selectArticleDialog.js
  src/components/singlePage/singlePage.css
  src/components/singlePage/singlePage.js
Labels: enhancement

#42 Fix segment entry bug
  README.md
  db.json
  package-lock.json
  package.json
  src/__tests__/OfferDisplay.js
  src/backendMock/db.json
  src/backendMock/routes.json
  src/components/alert/alert.js
  src/components/articleTable/articleTable.js
  src/components/connectionHandler/connectionHandler.js
  src/components/dynamicDialog/dynamicDialog.js
  src/components/layouts/backButton/backButton.js
  src/components/loading/loading.css
  src/components/loading/loading.js
  src/components/newEntrySegmentDialog/newEntrySegmentDialog.js
  src/components/newOfferDialog/newOfferDialog.js
  src/components/newProjectDialog/newProjectDialog.js
  src/components/offerDisplay/offerDisplay.js
  src/components/offerEntry/offerEntry.js
  src/components/projectCard/projectCard.js
  src/components/projectDisplay/projectDisplay.js
  src/components/selectArticleDialog/selectArticleDialog.js
  src/components/singlePage/singlePage.css
  src/components/singlePage/singlePage.js
  src/components/snackbar/snackbar.js
Labels: bugfix, enhancement

#43 Bug fixes and design changes
  README.md
  db.json
  package-lock.json
  package.json
  src/__tests__/OfferDisplay.js
  src/backendMock/db.json
  src/backendMock/routes.json
  src/components/alert/alert.js
  src/components/articleTable/articleTable.js
  src/components/connectionHandler/connectionHandler.js
  src/components/dynamicDialog/dynamicDialog.js
  src/components/layouts/backButton/backButton.js
  src/components/loading/loading.css
  src/components/loading/loading.js
  src/components/newEntrySegmentDialog/newEntrySegmentDialog.js
  src/components/newOfferDialog/newOfferDialog.js
  src/components/newProjectDialog/newProjectDialog.js
  src/components/offerDisplay/offerDisplay.js
  src/components/offerEntry/offerEntry.js
  src/components/projectCard/projectCard.js
  src/components/projectDisplay/projectDisplay.js
  src/components/selectArticleDialog/selectArticleDialog.js
  src/components/singlePage/singlePage.css
  src/components/singlePage/singlePage.js
  src/components/snackbar/snackbar.js
Labels: bugfix, enhancement
